version: "3.9"
services:
  frontendapp:
    build: ./frontend
    ports:
      - "9000:9000"
    links:
      - backendapp
    depends_on:
      - backendapp

  backendapp:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=dbpostgres
    depends_on:
      - dbpostgres

  dbpostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
