version: "3"

services:

  dbpostgres:
    image: postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/postgresql/data
    env_file:
      - ./database/database.env
    ports:
      - "5432:5432"
    networks:
      - app-network
    container_name: postgresqldatabase_service

  backendapp:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - DB_HOST=dbpostgres
    depends_on:
      - dbpostgres
    container_name: backendcrudposgresql_service

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
