version: "3.9"
services:

  backendapp:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=dbpostgres
    depends_on:
      - dbpostgres

  dbpostgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

volumes:
  postgres-data:
