version: "3"
services:
  frontend:
    image: ./frontend
    ports:
      - "9000:3000"
    depends_on:
      - backend

  backend:
    image: python:3.9-slim-buster
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
