version: "3"
services:

  dbpostgres:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/database.env
    ports:
      - "532:5432"
    networks:
      - app-network
    container_name: postgresql_service

  backendapp:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=dbpostgres
    depends_on:
      - dbpostgres

volumes:
  database-data:
